Update gauge_logic.js
fix for ```file:///var/task/src/logic/gauge_logic.js:4
import supabase, { supabaseRequest } from '../../lib/supabaseClient.js';
       ^^^^^^^^
SyntaxError: The requested module '../../lib/supabaseClient.js' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:177:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:260:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async d (/opt/rust/nodejs.js:16:18009)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.```